### ISSUE TITLE
Extract client functionality into separate sub-project 

### ISSUE THREAD

**Issue by terjedahl** [brehaut/necessary-evil#11]
The reason (in my case) is that I only want to consume an xmlrpc service, and I would like my dependency to remain as small as possible.  I.e. I don't need any of the ring server-side code, or whatever dependencies it in turn has.

**Comment by brehaut** [comment]
Not going to happen. I have no interest in tripling my maintenance workload for this project. 

But this is academic anyway. The project is open source; you don't need my permission to go make your own reduced fork.

**Comment by brehaut** [comment]
One more point: Ring is only included in the dev dependancies list – not the primary dependancies list – for running the test suite. If you wanted to use the server component you would need to depend on ring yourself explicitly.
